spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 151237643431-c05psmqkods7hkdbnm9vu7i2e268octi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: o_Lx_ns3dKqexHmokzmn
            client-secret: 0VEnU9rm1e
            client-name: naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          kakao:
            client-id: f75314d17e5e677058347b6b100e3a66
            client-secret: BplirZZgzkNb5v5Oh7AnhEkt8bs2AMXI
            client-name: kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile-nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
