--강아지

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '골든리트리버', '1살미만', '남아', '완료', 1, '경기도 안양시','온순','49623170','defaultimg/골든리트리버1.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '49623170'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '골든리트리버', '1살~5살', '남아', '미완료', 1.5, '경기도 안양시','사납','13589742','defaultimg/골든리트리버2.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '13589742'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '골든리트리버', '6살~9살', '여아', '알 수 없음', 1.7, '경기도 안양시','사납','37138947','defaultimg/골든리트리버3.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '37138947'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '골든리트리버', '10살이상', '여아', '미완료', 2.1, '경기도 안양시','겁이많음','61025678','defaultimg/골든리트리버4.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '61025678'
);
 
INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '진돗개', '1살미만', '남아', '알 수 없음', 1.1, '경기도 안양시','사납','34699872','defaultimg/진돗개1.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '34699872'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '진돗개', '1살~5살', '여아', '알 수 없음', 0.9, '경기도 안양시','겁이많음','13486794','defaultimg/진돗개2.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '13486794'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '진돗개', '6살~9살', '남아', '완료', 1, '경기도 안양시','겁이많음','12379864','defaultimg/진돗개3.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '12379864'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '진돗개', '10살이상', '여아', '미완료', 1.3, '경기도 안양시','사납','10024897','defaultimg/진돗개4.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '10024897'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '기타', '1살미만', '여아', '알 수 없음', 1.1, '경기도 안양시','온순','00043876','defaultimg/기타1.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '00043876'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '기타', '1살~5살', '남아', '완료', 1.6, '경기도 안양시','귀여움','46977778','defaultimg/기타2.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '46977778'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '기타', '6살~9살', '여아', '완료', 1.4, '경기도 안양시','온순','45397850','defaultimg/기타3.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '45397850'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'강아지', '기타', '10살이상', '남아', '미완료', 1.2, '경기도 안양시','귀여움','11387884','defaultimg/기타4.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '11387884'
);




