--고양이

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '러시안블루', '1살미만', '남아', '완료', 1, '경기도 안양시','온순','49623171','defaultimg/러시안블루1.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '49623171'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '러시안블루', '1살~5살', '남아', '미완료', 1.5, '경기도 안양시','사납','13589743','defaultimg/러시안블루2.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '13589743'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '러시안블루', '6살~9살', '여아', '알 수 없음', 1.7, '경기도 안양시','사납','37138948','defaultimg/러시안블루3.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '37138948'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '러시안블루', '10살이상', '여아', '미완료', 2.1, '경기도 안양시','겁이많음','61025679','defaultimg/러시안블루4.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '61025679'
);
 
INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '페르시안', '1살미만', '남아', '알 수 없음', 1.1, '경기도 안양시','사납','34699873','defaultimg/페르시안1.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '34699873'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '페르시안', '1살~5살', '여아', '알 수 없음', 0.9, '경기도 안양시','겁이많음','13486795','defaultimg/페르시안2.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '13486795'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '페르시안', '6살~9살', '남아', '완료', 1, '경기도 안양시','겁이많음','12379865','defaultimg/페르시안3.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '12379865'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '페르시안', '10살이상', '여아', '미완료', 1.3, '경기도 안양시','사납','10024898','defaultimg/페르시안4.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '10024898'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '기타', '1살미만', '여아', '알 수 없음', 1.1, '경기도 안양시','온순','00043877','defaultimg/기타5.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '00043877'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '기타', '1살~5살', '남아', '완료', 1.6, '경기도 안양시','귀여움','46977779','defaultimg/기타6.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '46977779'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '기타', '6살~9살', '여아', '완료', 1.4, '경기도 안양시','온순','45397851','defaultimg/기타7.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '45397851'
);

INSERT INTO animal(ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_AGE, ANIMAL_SEX, ANIMAL_NEUTERING, ANIMAL_WEIGHT, ANIMAL_REGION,ANIMAL_ETC,ANIMAL_CODE_NUMBER,ANIMAL_IMAGE, CREATED_TIME, UPDATE_TIME)
SELECT'고양이', '기타', '10살이상', '남아', '미완료', 1.2, '경기도 안양시','귀여움','11387885','defaultimg/기타8.jpg', SYSTIMESTAMP, SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (
    SELECT 1 
    FROM animal 
    WHERE ANIMAL_CODE_NUMBER = '11387885'
);




