-- 강아지 / 건사료 
INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '고스비 고양이사료', '고스비 고양이사료입니다.','defaultimg/고양이사료_고스비.jpg',20000,100,SYSTIMESTAMP,SYSTIMESTAMP );

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '나비엠알오 고양이사료', '나비엠알오 고양이사료입니다.','defaultimg/고양이사료_나비엠알오.jpg',9000,110,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '두나펫 고양이사료', '두나펫 고양이사료입니다.','defaultimg/고양이사료_두나펫.jpg',11000,130,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '리브레 고양이사료', '리브레 고양이사료입니다.','defaultimg/고양이사료_리브레.jpg',29000,5000,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '어덜트 고양이사료', '어덜트 고양이사료입니다.','defaultimg/고양이사료_어덜트.jpg',22000,150,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '캣블리 고양이사료', '캣블리 고양이사료입니다.','defaultimg/고양이사료_캣블리.jpg',32000,160,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '커클랜드 고양이사료', '커클랜드 고양이사료입니다.','defaultimg/고양이사료_커클랜드.jpg',16000,180,SYSTIMESTAMP,SYSTIMESTAMP);

INSERT INTO product(PRODUCT_ANIMAL_TYPE, PRODUCT_CATEGORY, PRODUCT_NAME, PRODUCT_CONTENT, PRODUCT_IMAGE,PRODUCT_PRICE,PRODUCT_READ_COUNT,CREATED_TIME, UPDATE_TIME) 
VALUES('고양이', '건사료', '쿠쿳 고양이사료', '쿠쿳 고양이사료입니다.','defaultimg/고양이사료_쿠쿳.jpg',19000,190,SYSTIMESTAMP,SYSTIMESTAMP);


--총 32개 기본데이터


commit;